package com.github.hugohomesquita.htmxjetbrains

object AttributeUtil {
    val attributes = arrayOf(
        "hx-boost",
        "hx-get",
        "hx-post",
        "hx-push-url",
        "hx-select",
        "hx-select-oob",
        "hx-swap",
        "hx-swap-oob",
        "hx-target",
        "hx-trigger",
        "hx-vals",
        "hx-confirm",
        "hx-delete",
        "hx-disable",
        "hx-disinherit",
        "hx-encoding",
        "hx-ext",
        "hx-headers",
        "hx-history",
        "hx-history-elt",
        "hx-include",
        "hx-indicator",
        "hx-params",
        "hx-patch",
        "hx-preserve",
        "hx-prompt",
        "hx-put",
        "hx-replace-url",
        "hx-request",
        "hx-sse",
        "hx-sync",
        "hx-validate",
        "hx-vars",
        "hx-ws",
    )
}